#ifndef CONTROLLER_TYPE_H
#define CONTROLLER_TYPE_H
#include "general.h"

enum class CONTROLLER_TYPE {
    VELOCITYPID = 0,
    VELOCITYRL = 1,
    ACCELERATIONPID = 2,
    GEOMETRIC = 3,
    ADAPTIVEGEOMETRIC = 4,
    JAEYOUNG = 5,
    BRESCIANINI = 6,
    KOOIJMAN = 7
};

#endif // CONTROLLER_TYPE_H

