from matrix_utils import hat, vee, deriv_unit_vector, saturate
from integral_utils import IntegralError, IntegralErrorVec3
from common import limitInclination

import time
import numpy as np

from math import sin, cos, pi, sqrt

###############################################################################################################
class GeometricControllerParameters:
    def __init__(self, mass=0.5):
        self.mass = mass  # Mass of the rover (kg)
        self.gravity = 9.81  # Gravitational acceleration (m/s^2)
        self.J = np.diag([0.03, 0.03, 0.055])  # Inertia matrix of the rover

            # controller
 
        # Position gains
        self.kX = np.diag([0.8, 0.8, 1.0])/2  # Position gains
        self.kV = np.diag([0.4, 0.4, 0.4])*2 # Velocity gains
        # Integral gains
        self.kIX = np.diag([0, 0, .8]) # Position integral gains
        self.kIV = np.diag([0.7, 0.7, 1]) # Velocity integral gains

        k_X = np.diag(self.kX)
        k_V = np.diag(self.kV)  
        # Parameters for Position decoupled-yaw integral control
        # self.c1 = np.min([np.sqrt(k_X / self.mass), 
        #                   4 * k_X * k_V / (k_V**2 + 4 * self.mass * k_X)],axis=0) # Parameters for Position decoupled-yaw integral control
        self.c1 = 1.0  

        # Attitude
        self.kR = np.diag([1, 1, 0.8])/2   # attitude error proportional gains
        self.kIR = np.diag([.1, .1, .1]) # attitude error integral gains
        # Yaw
        self.kW = np.diag([0.8, 0.8, 0.15])/2 # angular rate gains

        B2 = 1
        J1 = np.diag(self.J)[0]
        k_R = np.diag(self.kR)
        k_W = np.diag(self.kW)
        # self.c2 = np.min([np.sqrt(k_R / J1), 
        #                   4 * k_R * k_W / ((k_W + J1 * B2)**2 + 4 * J1 * k_R)],axis=0)
        self.c2 = 2.0  # Parameters for Attitude decoupled-yaw integral control

        # self.c3 = 2.0  # Parameters for Yaw decoupled-yaw integral control
       
        # Integral saturation limits
        self.sat_sigmaX = 2
        self.sat_sigmaV = 2
        self.sat_sigmaIR = 0.5
                
class GeometricController:
    """Controller for the UAV trajectory tracking.

    This class detemines the control outputs for a quadrotor UAV given it's
    current state and the desired states.

    Attributes:
        t0: (datetime object) time at epoch
        t: (float) current time since epoch [s]
        t_prev: (float) time since epoch in the previous loop [s]
        dt: (float) time difference between two calls to the controller [s]

        x: (3x1 numpy array) current position of the UAV [m]
        v: (3x1 numpy array) current velocity of the UAV [m/s]
        a: (3x1 numpy array) current acceleration of the UAV [m/s^s]
        R: (3x3 numpy array) current attitude of the UAV in SO(3)
        W: (3x1 numpy array) current angular velocity of the UAV [rad/s]

        xd: (3x1 numpy array) desired position of the UAV [m]
        xd_dot: (3x1 numpy array) desired velocity of the UAV [m/s]
        xd_2dot: (3x1 numpy array) desired accleration of the UAV [m/s^2]
        xd_3dot: (3x1 numpy array) desired third derivative of the UAV 
            position [m/s^3]
        xd_4dot: (3x1 numpy array) desired fourth derivative of the UAV 
            position [m/s^4]

        b1d: (3x1 numpy array) desired direction of the first body axis
        b1d_dot: (3x1 numpy array) first time derivative of the desired  
            direction of the first body axis
        b1d_2dot: (3x1 numpy array) second time desired direction of the first 
            body axis

        Wd: (3x1 numpy array) desired body angular velocity [rad/s]
        Wd_dot: (3x1 numpy array) desired body angular acceleration [rad/s^2]

        Rd: (3x3 numpy array) desired attitude in SO(3)

        b3d: (3x1 numpy array) desired direction of the third body axis
        b3d_dot: (3x1 numpy array)  first time derivative of the desired  
            direction of the third body axis
        b3d_2dot: (3x1 numpy array)  second time desired direction of the third 
            body axis

        b1c: (3x1 numpy array) calculated direction of the first body axis
        wc3: (float) angular velocity around third body axis [rad/s]
        wc3_dot: (float) angular acceleration around third body axis [rad/s^s]

        use_integral: (bool) flag to enable/disable integral control 

        e1 = (3x1 numpy array) direction of the e1 axis
        e2 = (3x1 numpy array) direction of the e2 axis
        e3 = (3x1 numpy array) direction of the e3 axis

        mass: (float) mass of the rover [kg]
        gravity: (float) gravitational acceleration [m/s^2]
        c_tf: (float) torsional moment generated by the propellers
        l: (float) length of the rover arm [m]
        J: (3x3 numpy array) inertia matrix of the rover

        kR: (3x3 numpy array) attitude gains
        kW: (3x3 numpy array) angular rate gains

        ky: (float) yaw gain for decoupled-yaw controller
        kwy: (float) yaw angular rate gain for decoupled-yaw controller

        kX: (3x3 numpy array) position gains
        kV: (3x3 numpy array) velocity gains

        kIR: (float) attitude integral gain
        ki: (float) position integral gain
        kI: (float) ttitude integral gain for roll and pitch
        kyI: (float) attitude integral gain for yaw
        kIX: (float) position integral gains
        c1: (float) parameters for decoupled-yaw integral control
        c2: (float) parameters for decoupled-yaw integral control
        c3: (float) parameters for decoupled-yaw integral control

        fM: (4x1 numpy array) force-moment vector
        f_total: (float) calculated forces required by each moter

        fM_to_forces: (4x4 numpy array) force to force-moment conversion
            matrix
        fM_to_forces_inv: (4x4 numpy array) force-moment to force conversion
            matrix

        eIX: (IntegralErrorVec3) position integral error
        eIR: (IntegralErrorVec3) attitude integral error

        sat_sigmaX
    """
###############################################################################################################

    def __init__(self, mass, use_integralTerm=True):
        
        self.controllerType = "Geometric"
        self.t0 = time.time()
        self.t = 0.0
        self.t_pre = 0.0
        self.dt = 1e-9
        
        self.omegaFactor = 0.1

        # Flag to enable/disable integral control 
        self.use_integralTerm = use_integralTerm

        self.e1 = np.zeros(3)
        self.e1[0] = 1.0
        self.e2 = np.zeros(3)
        self.e2[1] = 1.0
        self.e3 = np.zeros(3)
        self.e3[2] = 1.0

        self.param = GeometricControllerParameters(mass=mass)

            # controller
        
        # Integral errors
        self.eIX = IntegralErrorVec3()  # Position integral error
        self.eIV = IntegralErrorVec3()  # Velocity integral error
        self.eIR = IntegralErrorVec3()  # Attitude integral error

###############################################################################################################
    def resetIntegralErrorTerms(self):
        """Reset the integral error terms."""
        self.eIX.set_zero()
        self.eIV.set_zero()
        self.eIR.set_zero()
        
###############################################################################################################
    def getCommand(self, currentBodyState, desiredBodyState, controlType=None):
        """Position controller to determine desired attitude and angular rates
        to achieve the deisred states.

        This uses the controller defined in "Control of Complex Maneuvers
        for a Quadrotor UAV using Geometric Methods on SE(3)"
        URL: https://arxiv.org/pdf/1003.2005.pdf
        """
        if controlType is None:
            pos_control=True
            vel_control=True
        else:
            pos_control = controlType[0]
            vel_control = controlType[1]
            
        (pos_ned, vel_ned, accel_ned, omega_ned, quat_ned_bodyfrd) = currentBodyState
        # (pos_des_ned, vel_des_ned, accel_des_ned, b1d_ned) = desiredState
        (xd, xd_dot, xd_2dot, xd_3dot, xd_4dot) = desiredBodyState[0]
        (b1d, b1d_dot, b1d_2dot) = desiredBodyState[1] 
    
        e3 = self.e3

        mass = self.param.mass
        gravity = self.param.gravity
        kV = self.param.kV
        kIV = self.param.kIV
        posFactor = 1 if pos_control else 0
        kX = self.param.kX*posFactor
        kIX = self.param.kIX*posFactor

        self.update_current_time()
        self.dt = self.t - self.t_pre

        # Translational error functions
        
        eX = (pos_ned - xd) if pos_control else np.zeros(3)   # position error - eq (11)
        eV = vel_ned - xd_dot                            # velocity error - eq (12)

        # Position integral terms
        self.eIX.integrate(self.param.c1 * eX + eV, self.dt)                 # eq (13)
        self.eIX.error = saturate(self.eIX.error, -self.param.sat_sigmaX, self.param.sat_sigmaX)
        self.eIV.integrate(eV, self.dt)
        self.eIV.error = saturate(self.eIV.error, -self.param.sat_sigmaV, self.param.sat_sigmaV)

        if self.use_integralTerm:
            if not pos_control:
                kIX = np.zeros((3,3))       
            if not vel_control:
                kIV = np.zeros((3,3))  
        else:
            kIX = np.zeros((3,3))
            kIV = np.zeros((3,3))

        # Force 'f' along negative b3-axis -                                 eq (14)
        # This term equals to R.e3
        A = - kX @ eX \
            - kV @ eV \
            - kIX @ self.eIX.error \
            - kIV @ self.eIV.error \
            - mass * gravity * e3 \
            + mass * xd_2dot

        self.A=A
        
        R = quat_ned_bodyfrd.to_rotation_matrix()
        R_T = R.T 
        W = omega_ned

        hatW = hat(W)

        b3 = R @ e3
        b3_dot = R @ hatW @ e3                                             # eq (22)
        f_total = -A @ b3

        # Intermediate terms for rotational errors
        ea =  gravity * e3 \
            - f_total / mass * b3 \
            - xd_2dot 

        A_dot = - kX @ eV \
                - kV @ ea \
                - kIX @ self.eIV.error \
                + mass * xd_3dot

        fdot = - A_dot @ b3 \
            - A @ b3_dot
        eb = - fdot / mass * b3 - f_total / mass * b3_dot - xd_3dot              # eq (27)
        A_2dot = - kX @ ea \
                 - kV @ eb \
                 + mass * xd_4dot

        b3c, b3c_dot, b3c_2dot = deriv_unit_vector(-A, -A_dot, -A_2dot)

        hat_b1d = hat(b1d)
        hat_b1d_dot = hat(b1d_dot)

        A2 = -hat_b1d @ b3c
        A2_dot = - hat_b1d_dot @ b3c - hat_b1d @ b3c_dot
        A2_2dot = - hat(b1d_2dot) @ b3c \
            - 2.0 * hat_b1d_dot @ b3c_dot \
            - hat_b1d @ b3c_2dot

        b2c, b2c_dot, b2c_2dot = deriv_unit_vector(A2, A2_dot, A2_2dot)

        hat_b2c = hat(b2c)
        hat_b2c_dot = hat(b2c_dot)

        b1c = hat_b2c @ b3c
        b1c_dot = hat_b2c_dot @ b3c + hat_b2c @ b3c_dot
        b1c_2dot = hat(b2c_2dot) @ b3c \
            + 2.0 * hat_b2c_dot @ b3c_dot \
            + hat_b2c @ b3c_2dot

        Rc = np.vstack((b1c, b2c, b3c)).T
        Rc_dot = np.vstack((b1c_dot, b2c_dot, b3c_dot)).T
        Rc_2dot = np.vstack((b1c_2dot, b2c_2dot, b3c_2dot)).T

        Rc_T = Rc.T
        Wc = vee(Rc_T @ Rc_dot)

        hat_Wc = hat(Wc)
        Wc_dot = vee(Rc_T @ Rc_2dot - hat_Wc @ hat_Wc)

        W3 = np.dot(R * e3, Rc * Wc)
        W3_dot = np.dot(R * e3, Rc * Wc_dot) + np.dot(R * hat(W) * e3, Rc * Wc)

        Wd = Wc
        Wd_dot = Wc_dot

        # Roll / pitch
        b3d = b3c
        b3d_dot = b3c_dot
        b3d_2dot = b3c_2dot

        # Yaw
        b1c = b1c
        wc3 = e3 @ (R_T @ Rc @ Wc)
        wc3_dot = e3 @ (R_T @ Rc @ Wc_dot) \
            - e3 @ (hatW @ R_T @ Rc @ Wc)
        
        eR = 1 / 2 * vee(Rc.T @ R - R.T @ Rc);                   # (10)
        eW = W - R.T @ Rc @ Wc                                   # (11)
        
        self.eIR.integrate(eW + self.param.c2 * eR, self.dt) # eq (13)
        self.eIR.error = saturate(self.eIR.error, -self.param.sat_sigmaIR, self.param.sat_sigmaIR)
        if not self.use_integralTerm:                                                    
            self.param.kIR = np.zeros((3,3))
            
        M = - self.param.kR @ eR \
            - self.param.kW @ eW \
            - self.param.kIR @ self.eIR.error 
            # + hat(R.T @ Rc @ Wc) @ self.param.J @ R.T @ Rc @ Wc \
            # + self.param.J @ R.T @ Rc @ Wc_dot
               
        # with coupled yaw control
        R_desired=Rc
        Omega_desired=M 
        # Omega_dot_desired=Wd_dot

        return f_total, R_desired, Omega_desired
###############################################################################################################

    def update_current_time(self):
        """Update the current time since epoch."""
        self.t_pre = self.t

        self.t = time.time() - self.t0
    



