from matrix_utils import hat, vee, deriv_unit_vector, saturate
from integral_utils import IntegralError, IntegralErrorVec3

import time
import numpy as np

from math import sin, cos, pi, sqrt

###############################################################################################################
class AdaptiveGeometricConstrainedControllerParams:
    def __init__(self, mass=0.5):
        self.use_disturbances = True

        self.mass = mass  # Mass of the rover (kg)
        self.gravity = 9.81  # Gravitational acceleration (m/s^2)
        self.J = np.diag([0.03, 0.03, 0.055])  # Inertia matrix of the rover


        self.d = 0.169      # Length of the rover arm (m)
        self.c_tf = 0.0135  # Torsional moment coefficient generated by the propellers

        # Fixed disturbance
        if self.use_disturbances:
            self.W_x = np.eye(3)
            self.theta_x = np.array([1, 0.8, -1])

            self.W_R = np.eye(3)
            self.theta_R = np.array([0.1, 0.1, -0.1])
        else:
            self.W_x = np.zeros(3)
            self.theta_x = np.array([0, 0, 0])

            self.W_R = np.eye(3)
            self.theta_R = np.array([0, 0, 0])
        ## Controller gains

            # controller
 
        # Position gains
        self.kX = np.diag([0.8, 0.8, 1.0])  # Position gains
        self.kV = np.diag([0.4, 0.4, 0.4]) # Velocity gains
        # Integral gains
        self.kIX = np.diag([0, 0, .8]) # Position integral gains
        self.kIV = np.diag([0.7, 0.7, 1]) # Velocity integral gains
        # Differentiation gains
        self.kDV = np.diag([.1, .1, .1])
        self.c1 = 1.0  # Parameters for Position decoupled-yaw integral control

        # Attitude
        self.kR = np.diag([1, 1, 0.8])   # attitude error proportional gains
        self.kIR = np.diag([.1, .1, .1]) # attitude error integral gains
        self.c2 = 2.0  # Parameters for Attitude decoupled-yaw integral control

        # Yaw
        self.kW = np.diag([0.8, 0.8, 0.15]) # angular rate gains
        self.c3 = 2.0  # Parameters for Yaw decoupled-yaw integral control
       
        # Integral saturation limits
        self.sat_sigmaX = 2
        self.sat_sigmaV = 2
        self.sat_sigmaIR = 0.5
        
        # Adaptive terms
        self.gamma_x = 2
        self.gamma_R = 10
        self.B_theta_x = 10
        ##
        k_X = np.diag(self.kX)
        k_V = np.diag(self.kV)
        self.c1 = np.min([np.sqrt(k_X / self.mass), 
                          4 * k_X * k_V / (k_V**2 + 4 * self.mass * k_X)],axis=0) # Parameters for Position decoupled-yaw integral control
        # self.c1 = 1.0  
        
        B2 = 1
        J1 = np.diag(self.J)[0]
        k_R = np.diag(self.kR)
        k_W = np.diag(self.kW)
        self.c2 = np.min([np.sqrt(k_R / J1), 
                          4 * k_R * k_W / ((k_W + J1 * B2)**2 + 4 * J1 * k_R)])
        self.c2 = 2.0  # Parameters for Attitude decoupled-yaw integral control

        J3 = np.diag(self.J)[2]
        k_y = np.diag(self.kR)[2]
        k_wy = np.diag(self.kW)[2]
        self.c3 = np.min([np.sqrt(k_y / J3), 
                          4 * k_y * k_wy / (k_wy**2 + 4 * J3 * k_y)])  
   
        # Integral saturation limits
        self.sat_sigmaX = 2
        self.sat_sigmaV = 2
        self.sat_sigmaIR = 0.5
        
class AdaptiveGeometricConstrainedController:
# Geometric adaptive tracking control of a quadrotor unmanned aerial 
# vehicle on {SE(3)}, F. Goodarzi, D. Lee, and T. Lee.
# Based on: 2010, Taeyoung Lee, Melvin Leok, and N. Harris McClamroch
# "Geometric tracking control of a quadrotor UAV on SE(3)"
#  https://ieeexplore.ieee.org/abstract/document/5717652
#
# The control law is based on the attitude control law for rigid bodies
# with a coupling term that depends on the desired angular velocity
# and its derivative.
################################################################################################################

    def __init__(self, mass, use_integralTerm=True):

        self.controllerType = "AdaptiveGeometricController"
        self.t0 = time.time()
        self.t = 0.0
        self.t_pre = 0.0
        self.dt = 1e-9
        
        self.bar_theta_x = np.zeros(3)
        self.bar_theta_R = np.zeros(3)

        # Flag to enable/disable integral control 
        self.use_integralTerm = use_integralTerm

        self.e1 = np.zeros(3)
        self.e1[0] = 1.0
        self.e2 = np.zeros(3)
        self.e2[1] = 1.0
        self.e3 = np.zeros(3)
        self.e3[2] = 1.0

        self.param = AdaptiveGeometricConstrainedControllerParams(mass=mass)
        
        # Integral errors
        self.eIX = IntegralErrorVec3()  # Position integral error
        self.eIV = IntegralErrorVec3()  # Velocity integral error
        self.eIR = IntegralErrorVec3()  # Attitude integral error

###############################################################################################################
    def resetIntegralErrorTerms(self):
        """Reset the integral error terms."""
        self.eIX.set_zero()
        self.eIV.set_zero()
        self.eIR.set_zero()

###############################################################################################################

    def getCommand(self, currentBodyState, desiredBodyState, controlType=None):
        """
        2017, Lee, Constrained Geometric Attitude Control on SO(3)
        """
        if controlType is None:
            pos_control=True
            vel_control=True
        else:
            pos_control = controlType[0]
            vel_control = controlType[1]
        
        (pos_ned, vel_ned, accel_ned, omega_ned, quat_ned_bodyfrd) = currentBodyState
        # (pos_des_ned, vel_des_ned, accel_des_ned, b1d_ned) = desiredState
        (xd, xd_dot, xd_2dot, xd_3dot, xd_4dot) = desiredBodyState[0]
        (b1d, b1d_dot, b1d_2dot) = desiredBodyState[1] 
   
        e3 = self.e3

        mass = self.param.mass
        gravity = self.param.gravity
        kV = self.param.kV
        kIV = self.param.kIV
        kDV = self.param.kDV
        posFactor = 1 if pos_control else 0
        kX = self.param.kX*posFactor
        kIX = self.param.kIX*posFactor
            
        self.update_current_time()
        self.dt = self.t - self.t_pre
        
        W_x = self.param.W_x
        W_x_dot = np.zeros((3,3))
        W_x_2dot = np.zeros((3,3))

        eX = (pos_ned - xd) if pos_control else np.zeros(3)
        eV = vel_ned - xd_dot

        # Position integral terms
        self.eIX.integrate(self.param.c1 * eX + eV, self.dt)                 # eq (13)
        self.eIX.error = saturate(self.eIX.error, -self.param.sat_sigmaX, self.param.sat_sigmaX)
        self.eIV.integrate(eV, self.dt)
        self.eIV.error = saturate(self.eIV.error, -self.param.sat_sigmaV, self.param.sat_sigmaV)

        if self.use_integralTerm:
            if not pos_control:
                kIX = np.zeros((3,3))       
            if not vel_control:
                kIV = np.zeros((3,3))  
        else:
            kIX = np.zeros((3,3))
            kIV = np.zeros((3,3))

        A = - kX @ eX \
            - kV @ eV \
            - kIX @ self.eIX.error \
            - kIV @ self.eIV.error \
            - mass * gravity * e3 \
            + mass * xd_2dot \
            - W_x @ self.bar_theta_x
        self.A=A

        R = quat_ned_bodyfrd.to_rotation_matrix()
        W = omega_ned
        
        gamma_x = self.param.gamma_x

        ev_c1ex = eV + self.param.c1 * eX

        norm_theta_x = np.linalg.norm(self.bar_theta_x)
        if norm_theta_x < self.param.B_theta_x or \
            (norm_theta_x == self.param.B_theta_x and self.bar_theta_x.T @ W_x.T @ ev_c1ex <= 0):
            
            bar_theta_x_dot = gamma_x * W_x.T @ ev_c1ex
        else:
            I_theta = np.eye(3) - self.bar_theta_x @ self.bar_theta_x.T / (self.bar_theta_x.T @ self.bar_theta_x)
            bar_theta_x_dot = gamma_x * I_theta @ W_x.T @ ev_c1ex
        
        b3 = R @ e3
        f_total = -A.T @ b3
        ev_dot =  gravity * e3 \
                - f_total / mass * b3 \
                - xd_2dot \
                + W_x @ self.bar_theta_x / mass
        A_dot = - kX @ eV \
                - kV @ ev_dot \
                + mass * xd_3dot \
                - W_x_dot @ self.bar_theta_x \
                - W_x @ bar_theta_x_dot
        
        norm_theta_x = np.linalg.norm(self.bar_theta_x)
        if norm_theta_x < self.param.B_theta_x or \
            (norm_theta_x == self.param.B_theta_x and self.bar_theta_x.T @ W_x.T @ ev_c1ex <= 0):
            
            bar_theta_x_2dot = gamma_x * W_x_dot.T @ ev_c1ex \
                                + gamma_x * W_x.T @ (ev_dot + self.param.c1 * eV)
        else:
            I_theta = np.eye(3) \
                        - self.bar_theta_x @ self.bar_theta_x.T / (self.bar_theta_x.T @ self.bar_theta_x)
            
            num = norm_theta_x * (bar_theta_x_dot @ self.bar_theta_x.T \
                                + self.bar_theta_x @ bar_theta_x_dot.T) \
                                - 2 * (self.bar_theta_x @ self.bar_theta_x.T) @ bar_theta_x_dot
            I_theta_dot = - num / norm_theta_x**3
            bar_theta_x_2dot = gamma_x * I_theta_dot @ W_x.T @ ev_c1ex \
                                + gamma_x * I_theta @ W_x_dot.T @ ev_c1ex \
                                + gamma_x * I_theta @ W_x.T @ (ev_dot + self.c1 * eV)
        
        b3_dot = R @ hat(W) @ e3   # W_z in NED coordinate frame (check if W is in body frame)
        f_dot = -A_dot.T @ b3 - A.T @ b3_dot
        ev_2dot = - f_dot / mass * b3 \
                  - f_total / mass * b3_dot - xd_3dot \
                  + W_x_dot @ self.bar_theta_x / mass \
                  + W_x @ bar_theta_x_dot / mass
        A_ddot = - kX @ ev_dot \
                - kV @ ev_2dot \
                + mass * xd_4dot \
                - W_x_2dot @ self.bar_theta_x \
                - 2 * W_x_dot @ bar_theta_x_dot \
                - W_x @ bar_theta_x_2dot
        
        b3c, b3c_dot, b3c_ddot = deriv_unit_vector(-A, -A_dot, -A_ddot)

        A2 = -hat(b1d) @ b3c
        A2_dot = -hat(b1d_dot) @ b3c - hat(b1d) @ b3c_dot
        A2_ddot = - hat(b1d_2dot) @ b3c \
                    - 2 * hat(b1d_dot) @ b3c_dot \
                    - hat(b1d) @ b3c_ddot

        b2c, b2c_dot, b2c_ddot = deriv_unit_vector(A2, A2_dot, A2_ddot)

        b1c = hat(b2c) @ b3c
        b1c_dot = hat(b2c_dot) @ b3c + hat(b2c) @ b3c_dot
        # b1c_ddot = hat(b2c_ddot) @ b3c \
        #             + 2 * hat(b2c_dot) @ b3c_dot \
        #             + hat(b2c) @ b2c_ddot
        
        Rc = np.vstack((b1c, b2c, b3c)).T
        Rc_dot = np.vstack((b1c_dot, b2c_dot, b3c_dot)).T
        # Rc_ddot = np.vstack((b1c_ddot, b2c_ddot, b3c_ddot)).T
        
        Wc = vee(Rc.T @ Rc_dot)
        # hat_Wc = hat(Wc)
        # Wc_dot = vee(Rc.T @ Rc_ddot - hat_Wc @ hat_Wc)
        
        # W3 = (R @ e3).T @ (Rc @ Wc)
        # W3_dot = (R @ e3).T @ (Rc @ Wc_dot) + (R @ hat(W) @ e3).T @ (Rc @ Wc)
        
        """Run attitude controller (couplrd)"""

        eR = 1 / 2 * vee(Rc.T @ R - R.T @ Rc);                   # (10)
        eW = W - R.T @ Rc @ Wc                                   # (11)
        M = - self.param.kR @ eR \
            - self.param.kW @ eW \
            - self.param.W_R @ self.bar_theta_R \
        #     + hat(R.T @ Rc @ Wc) @ self.param.J @ R.T @ Rc @ Wc \
        #     + self.param.J @ R.T @ Rc @ Wc_dot

        # dot_theta_R = self.param.gamma_R * self.param.W_R.T @ (eW + self.param.c2 * eR)
    
        # with coupled yaw control
        R_desired = Rc
        Omega_desired = M
        return f_total, R_desired, Omega_desired
###############################################################################################################

    def update_current_time(self):
        """Update the current time since epoch."""
        self.t_pre = self.t

        self.t = time.time() - self.t0
    

